name: CI for Spring Boot and React

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11' # Adjust the Java version as needed
        distribution: 'adoptopenjdk'

    - name: Build Spring Boot with Maven
      run: |
        cd path/to/spring-boot-project
        mvn clean install --batch-mode

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' # Adjust the Node.js version as needed

    - name: Install dependencies for React
      run: |
        cd path/to/react-project
        npm install

    - name: Build React project
      run: |
        cd path/to/react-project
        npm run build

    - name: Run tests for Spring Boot
      run: |
        cd path/to/spring-boot-project
        mvn test --batch-mode

    - name: Run tests for React
      run: |
        cd path/to/react-project
        npm test
